dist: trusty # 5.8 and 5.10 are missing from the default dist (currently Xenial for perl)
language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.20"
  - "5.30"
  - "5.32" # not available yet
matrix:
  allow_failures:
    - perl: "5.32"
