--- #YAML:1.0
name:               true
version:            0.16
abstract:           automatically return a true value when a file is required
author:
    - chocolateboy <chocolate@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    B::Hooks::OP::Annotation:  0.43
    B::Hooks::OP::Check:  0.18
    ExtUtils::Depends:    0.304
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Hooks::OP::Annotation:  0.43
    B::Hooks::OP::Check:  0.18
    Devel::StackTrace:    1.27
resources:
    repository:  http://github.com/chocolateboy/true
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
