---
abstract: 'automatically return a true value when a file is required'
author:
  - 'chocolateboy <chocolate@cpan.org>'
build_requires:
  Function::Parameters: '2.001003'
  Moo: '2.003004'
configure_requires:
  B::Hooks::OP::Annotation: '0.44'
  B::Hooks::OP::Check: '0.22'
  ExtUtils::Depends: '0.405'
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: 'true'
no_index:
  directory:
    - t
    - inc
requires:
  B::Hooks::OP::Annotation: '0.44'
  B::Hooks::OP::Check: '0.22'
  Devel::StackTrace: '2.03'
  perl: '5.008'
resources:
  bugtracker: https://github.com/chocolateboy/true/issues
  repository: https://github.com/chocolateboy/true
version: '0.18'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
