name: test

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
      - '**.pod'

env:
  CI: true

jobs:
  test:
    name: 'Perl v${{ matrix.perl }} on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        perl: ['5.8', '5.10', '5.20', '5.30', '5.32']

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up perl v${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - run: perl -V

        # this also upgrades ExtUtils::MakeMaker to the latest version
      - run: cpanm --notest Test::Pod

      - run: cpanm --installdeps --notest .
      - run: perl Makefile.PL
      - run: make test
